# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19eb68541a17f1a9b3d9535ed32c2c0680b83d808f76876675bf26f4417ae805407775a57b22808485250448303cd0a21807f73ec2c1dbe1f2e9d76b5f99092f

test:
  secret_key_base: 863198a5100dccf8b53eb9d73d7ede6b665af1aab32a0c197953b676f48cabe9a36b49b4a9c4c43930953f145516553bab0e95517543543d010b09aac9b48b23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
